/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.login;
import model.login;
import view.TelaLogin;

/**
 *
 * @author Luisr
 */
public class TelaCadastro extends javax.swing.JFrame {
private login login;
private login senha;
private login username;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cPainel = new javax.swing.JPanel();
        cdSenha = new javax.swing.JTextField();
        cdUsuario = new javax.swing.JTextField();
        cdNome = new javax.swing.JTextField();
        tNome = new javax.swing.JLabel();
        nUsuario = new javax.swing.JLabel();
        nSenha = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        bCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cPainel.setBackground(new java.awt.Color(44, 42, 80));
        cPainel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cdSenha.setColumns(30);
        cdSenha.setActionCommand("<Not Set>");
        cdSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cdSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdSenhaActionPerformed(evt);
            }
        });

        cdUsuario.setColumns(30);
        cdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdUsuarioActionPerformed(evt);
            }
        });

        cdNome.setColumns(30);
        cdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdNomeActionPerformed(evt);
            }
        });

        tNome.setForeground(new java.awt.Color(255, 255, 255));
        tNome.setText("Nome:");

        nUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nUsuario.setText("Login:");

        nSenha.setForeground(new java.awt.Color(255, 255, 255));
        nSenha.setText("Senha:");

        btVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        bCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        bCadastrar.setText("Cadastrar");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cPainelLayout = new javax.swing.GroupLayout(cPainel);
        cPainel.setLayout(cPainelLayout);
        cPainelLayout.setHorizontalGroup(
            cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cPainelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(bCadastrar)
                .addGap(80, 80, 80))
            .addGroup(cPainelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nSenha)
                    .addComponent(tNome)
                    .addComponent(nUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cdNome, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(cdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(cdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cPainelLayout.setVerticalGroup(
            cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPainelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNome))
                .addGap(18, 18, 18)
                .addGroup(cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nUsuario)
                    .addComponent(cdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nSenha))
                .addGap(60, 60, 60)
                .addGroup(cPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(bCadastrar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cPainel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cPainel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdUsuarioActionPerformed
             
    }//GEN-LAST:event_cdUsuarioActionPerformed

    private void cdSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdSenhaActionPerformed
   
    }//GEN-LAST:event_cdSenhaActionPerformed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
            username = new username();
            username.setUsername(cdNome.getText());
            senha = new login();
            senha.setSenha(cdSenha.getText());
            login = new login();
            login.setLogin(cdUsuario.getText());
            
            
            
       
            if(senha.equals(null)){
                JOptionPane.showMessageDialog(null, "Por favor digite uma senha");
            
            }if(login.equals(null)){
                JOptionPane.showMessageDialog(null, "Por favor digite um login");
            }
            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
             new TelaLogin().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_bCadastrarActionPerformed
   
 
    
    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void cdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdNomeActionPerformed
       
    }//GEN-LAST:event_cdNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel cPainel;
    private javax.swing.JTextField cdNome;
    private javax.swing.JTextField cdSenha;
    private javax.swing.JTextField cdUsuario;
    private javax.swing.JLabel nSenha;
    private javax.swing.JLabel nUsuario;
    private javax.swing.JLabel tNome;
    // End of variables declaration//GEN-END:variables

    private static class username extends login {

        public username() {
        }
    }
}
